services:
  redis:
    image: redis:alpine
    restart: always

  weather:
    image: ghcr.io/angelkae7/meteo-app:latest
    build: .
    depends_on:
      - redis
    restart: always
    ports:
      - "80:80"
